name: ofpptemploidetemp

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Test with pytest
      run: pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: ofpptemploidetemp
      uses: azure/webapps-deploy@v2
      with:
        app-name: <your-app-name>
        slot-name: <your-slot-name> # optional
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
